//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LMS.rc
//
#define IDOK2                           3
#define IDC_CONFORM                     3
#define IDD_ABOUTBOX                    100
#define IDD_LMS_FORM                    101
#define IDR_MAINFRAME                   128
#define IDR_LMSTYPE                     129
#define IDD_DIALOG_LOGIN                130
#define IDB_Book                        131
#define IDB_No                          132
#define IDB_Yes                         133
#define IDI_ICON1                       134
#define IDD_DIALOG_BOOKM                141
#define IDB_BITMAP3                     142
#define IDB_BG                          155
#define IDD_DIALOG_RADER                156
#define IDD_DIALOG_INFO                 157
#define IDI_PEOPLEM                     159
#define IDI_BOOKM                       160
#define IDI_EXIT0                       162
#define IDB_BGfront                     163
#define IDI_EXIT                        170
#define IDI_DELETE                      171
#define IDI_MODIFY                      172
#define IDI_ADDBOOK                     173
#define IDI_PRINT                       174
#define IDI_REFRESH                     175
#define IDI_CLOSE                       176
#define IDI_MANAGE                      177
#define IDI_SEARCH                      179
#define IDI_QUERY                       180
#define IDI_EXPORT                      181
#define IDR_MENU                        185
#define IDR_MENUQUERY                   186
#define IDR_MENUMANAGE                  187
#define IDD_QUERYREADERREASON           188
#define IDD_DIALOG_BORROWBOOK           189
#define IDD_DIALOG_NEWBOOK              190
#define IDD_DIALOG_NEWREADER            191
#define IDD_DIALOG_DELETEREADER         192
#define IDD_DIALOG_DELETEBOOK           193
#define IDD_DIALOG_PUNISHMENT           194
#define IDD_DIALOG_QUERYREADER          195
#define IDD_DIALOG_MODIFYPASSWORD       197
#define IDD_DIALOG_USER                 199
#define IDD_DIALOG_EXPORT               201
#define IDD_DIALOG_MODIFYINFO           202
#define IDB_F7                          203
#define IDB_F2                          204
#define IDB_F5                          205
#define IDB_F3                          206
#define IDB_F1                          207
#define IDB_F8                          208
#define IDB_F6                          209
#define IDB_F4                          210
#define IDD_DIALOG_RENEWAL              211
#define IDD_DIALOG_QUERY                212
#define IDD_DIALOG_BORROWRECORD         213
#define IDD_DIALOG_CANCELRENEWAL        214
#define IDD_DIALOG_PUNISHRECORD         216
#define IDD_DIALOG_MODIFYBOOK           217
#define IDD_DIALOG_MODITYREADER         218
#define IDD_DIALOG_MODIFYREADER         228
#define IDD_DIALOG_DEMPTMANAGE          229
#define IDD_DIALOG_BORROWMANAGE         230
#define IDD_DIALOG_DATABASEMANAGE       231
#define IDB_BITMAP1                     232
#define IDB_BITMAP2                     233
#define IDD_DIALOG_ADMINMANAGE          234
#define IDD_DIALOG_ADDNEWADMIN          235
#define IDD_DIALOG_BOOKBOOK             236
#define IDD_DIALOG_RETURNBOOK           237
#define IDD_DIALOG_DATABASEBACKUP       238
#define IDD_DIALOG_BOOKSORT             239
#define IDD_DIALOG_NINDEX               240
#define IDR_MENURCLICK                  241
#define IDD_DIALOG_CLASSMODIFY          242
#define IDB_BITMAP4                     243
#define IDD_DIALOG_Look                 244
#define IDB_BITMAP5                     246
#define IDB_BITMAP6                     248
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_STATIC3                     1002
#define IDC_EDIT6                       1002
#define IDC_STATIC1                     1003
#define IDC_EDIT11                      1003
#define IDC_STATIC2                     1004
#define IDC_OK1                         1005
#define IDC_CANCEL1                     1006
#define IDC_BUTTON1                     1007
#define IDC_OPEN                        1007
#define IDC_PERSONINFO                  1007
#define IDC_BUTTON2                     1008
#define IDC_ADDNEW                      1008
#define IDC_BOOKQUERY                   1008
#define IDC_RENEWAL                     1008
#define IDC_DELAY2                      1008
#define IDC_DELAY                       1008
#define IDC_QUERYBOOK                   1008
#define IDC_STATIC4                     1009
#define IDC_BUTTON3                     1009
#define IDC_ADDTO                       1009
#define IDC_QUERYREADER                 1009
#define IDC_DATACOPY                    1009
#define IDC_BOOK_BOOK                   1010
#define IDC_RETURNBOOK                  1010
#define IDC_DATALOGCOPY                 1010
#define IDC_BUTTON4                     1010
#define IDC_PUNISHMENTRECORD            1011
#define IDC_DELETEBOOK                  1011
#define IDC_BUTTON6                     1012
#define IDC_DELAYBOOK                   1012
#define IDC_BORROWRECORD                1013
#define IDC_CANCELRENEWAL               1014
#define IDC_DELETEREADER                1014
#define IDC_PUNISHMENT                  1015
#define IDC_ADDNEWREADER                1016
#define IDC_ADDNEWBOOK1                 1017
#define IDC_ADDNEWBOOK                  1017
#define IDC_COMBO2                      1035
#define IDC_EDIT3                       1036
#define IDC_EDIT4                       1037
#define IDC_EDIT5                       1038
#define IDC_COMBO4                      1039
#define IDC_EDIT10                      1039
#define IDC_COMBO5                      1040
#define IDC_COMBO3                      1041
#define IDC_WRITER                      1041
#define IDC_EDIT9                       1041
#define IDC_COMBO7                      1042
#define IDC_PLEACE                      1042
#define IDC_NUM                         1043
#define IDC_COMBO6                      1044
#define IDC_EDIT7                       1045
#define IDC_EDIT8                       1046
#define IDC_STATICTag                   1047
#define IDC_VERSION                     1047
#define IDC_RADIO1                      1048
#define IDC_TIME                        1048
#define IDC_RADIO2                      1049
#define IDC_BookM                       1050
#define IDC_PeopleM                     1051
#define IDC_BORROWREASON                1052
#define IDC_Exit                        1053
#define IDC_ADDBOOK                     1054
#define IDC_DATABASEM                   1054
#define IDC_MODIFY                      1055
#define IDC_DEPTM                       1055
#define IDC_REFRESH                     1056
#define IDC_DELETE                      1057
#define IDC_QUERY                       1058
#define IDC_PRINT                       1059
#define IDC_EXPORT                      1060
#define IDC_MANAGE                      1061
#define IDC_COMBOINFO                   1062
#define IDC_CLOSE                       1063
#define IDC_SEARCH                      1064
#define IDC_EDITINFO                    1065
#define IDC_BOOKmanage                  1066
#define IDC_LIST                        1075
#define IDC_LIST1                       1077
#define IDC_BORROWBOOK1                 1078
#define IDC_BORROWBOOK                  1078
#define IDC_LIST4                       1078
#define IDC_COMBO1                      1080
#define IDC_COMBO8                      1081
#define IDC_ADDREADER                   1082
#define IDC_DATETIMEPICKER1             1087
#define IDC_ISBN                        1088
#define IDC_CONCENTS                    1089
#define IDC_NAME                        1090
#define IDC_PUBLISH                     1091
#define IDC_PRICE                       1092
#define IDC_TWO                         1093
#define IDC_ONE                         1094
#define IDC_REMARKS                     1095
#define IDC_CHECK1                      1098
#define IDC_CHECK2                      1099
#define IDC_CHECK3                      1100
#define IDC_CHECK4                      1101
#define IDC_IMPORT                      1102
#define IDC_OTHER                       1103
#define IDC_FEE                         1104
#define IDC_IDNO                        1105
#define IDC_MODIFYPWD                   1106
#define IDC_LIST2                       1107
#define IDC_BORROWBOOK2                 1109
#define IDC_DELAY1                      1110
#define IDC_STORE                       1117
#define IDC_LIST3                       1118
#define IDC_MONTHCALENDAR1              1119
#define IDC_TREE1                       1121
#define IDC_ADD                         1122
#define IDC_DATADIFFCOPY                1123
#define IDC_BUTTON5                     1124
#define IDC_RETURN                      1125
#define IDC_EDIT                        1126
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32774                32774
#define ID_QUERYREADERALL               32775
#define ID_QUERYREASON                  32776
#define ID_EXCELIMPORT                  32777
#define ID_ACCESSIMPORT                 32778
#define ID_MODIFY                       32779
#define ID_DELETE                       32780
#define ID_INDICATOR_LOGININFO          61446
#define ID_INDICATOR_TIME               61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        249
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
